config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  get "home/index"
  resources :coins

  root to: "home#index"

  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: %i[ new edit create update ]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy!

    respond_to do |format|
      format.html { redirect_to coins_path, status: :see_other, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params.expect(:id))
    end

    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description,:acronym,:url_image, :mining_type_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy!

    respond_to do |format|
      format.html { redirect_to mining_types_path, status: :see_other, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.expect(mining_type: [ :description, :acronym ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def locale
    I18n.locale == :en ? "en" : "pt-BR"
  end
  
  def convert_to_date_br(date)
    date.strftime("%d/%m/%Y")
  end

end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <p>
    <strong> <%= t('desctiption')%>:</strong>
    <%= coin.description %>
  </p>

  <p>
    <strong><%= t('acronym')%>:</strong>
    <%= coin.acronym %>
  </p>

  <p>
    <strong><%= t('url_image')%>:</strong>
    <%= coin.url_image %>
  </p>

</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description, t('desctiption'), style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :acronym,t('acronym'), style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div class ="field">
    <%= form.label :url_image, t('url_image'), style: "display: block" %>
    <%= form.text_field :url_image %>
  </div>

  <div class="field">
    <%= form.label :mining_type_id, t('mining_type') ,style: "display: block" %>
    <%= form.select("mining_type_id", @mining_type_options, {include_blank: 'select...'} ) %>
  </div>

  <div class="actions">
    <%= form.submit t('crud.submit')%>
  </div>
<% end %>

app/views/coins/edit.html.erb
<% content_for :title, "Editing coin" %>

<h1> <%= t('edit.coin') %> </h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t('crud.show'), @coin %> |
  <%= link_to t('back.coins'), coins_path %>
</div>

app/views/coins/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Coins" %>

<h1><%= t('coins') %></h1>

<table>

  <thead>
    <tr>
      <th style="padding-right: 30px;"><%= t('name') %></th>
      <th style = "padding-right: 30px;"> <%= t('symbol') %> </th>
      <th > <%= t('image') %></th>
      <th ></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td "><%= coin.acronym %></td>
        <td ><%= image_tag coin.url_image, size: "30x30" %></td>
        <td>
          <%= link_to t('crud.show'), coin_path(coin) %>
          <%= link_to t('crud.edit'), edit_coin_path(coin) %>
          <%= link_to t('crud.delete'), coin_path(coin), method: :delete, data: { confirm: t('crud.confirm_delete') } %>
      </tr>
    <% end %>
  </tbody>

</table>

<div class = "field">
<p> <%= link_to t('new.coin'), new_coin_path %> </p>
</div>

app/views/coins/new.html.erb
<% content_for :title, t('new.coin') %>

<h1><%= t('new.coin')%></h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t('back.coins'), coins_path %>
</div>

app/views/coins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @coin %>

<div class="actions">

  <%= link_to t('edit.coin'), edit_coin_path(@coin) %> |
  <%= link_to t('back.coins'), coins_path %>

</div>
<br>
<div class="field">

<%= button_to t('crud.delete'), @coin, method: :delete %>
</div>

app/views/home/_welcome.html.erb
<h1>WELCOME</h1>

<p>O idioma utilizada nesta aplicação é: <%= I18n.locale %></p>

<p <strong> <%= l(Date.today)%> </strong></p>

app/views/home/index.html.erb
<%= render "welcome" %>

<%=link_to "Register Coin", coins_path%>
<br>
<%=link_to"Register oin Mining Type", mining_types_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Crypto Wallet" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :acronym, style: "display: block" %>
    <%= form.text_field :acronym %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">
  <p>
    <strong>Description:</strong>
    <%= mining_type.description %>
  </p>

  <p>
    <strong>Acronym:</strong>
    <%= mining_type.acronym %>
  </p>

</div>

app/views/mining_types/edit.html.erb
<% content_for :title, "Editing mining type" %>

<h1>Editing mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Show this mining type", @mining_type %> |
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Mining types" %>

<h1>Mining types</h1>

<div id="mining_types">
  <% @mining_types.each do |mining_type| %>
    <%= render mining_type %>
    <p>
      <%= link_to "Show this mining type", mining_type %>
    </p>
  <% end %>
</div>

<%= link_to "New mining type", new_mining_type_path %>

app/views/mining_types/new.html.erb
<% content_for :title, "New mining type" %>

<h1>New mining type</h1>

<%= render "form", mining_type: @mining_type %>

<br>

<div>
  <%= link_to "Back to mining types", mining_types_path %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mining_type %>

<div>
  <%= link_to "Edit this mining type", edit_mining_type_path(@mining_type) %> |
  <%= link_to "Back to mining types", mining_types_path %>

  <%= button_to "Destroy this mining type", @mining_type, method: :delete %>
</div>